addons:
    apt:
      update: true
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements-dev.txt
# command to run tests
before_script:
  - ls -l
  - python mezger_farms/manage.py migrate
  - python mezger_farms/manage.py makemigrations
  - python mezger_farms/manage.py migrate
script: pytest
